apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-deploy
  template:
    metadata:
      labels:
        app: comment-deploy
    spec:
      containers:
      - name: app
        image: YOUR_DOCKER_USER/comment-deploy:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
spec:
  type: NodePort
  selector:
    app: comment-deploy
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
